parameters:
    pim_magento_connector.reader.category.class:                  Pim\Bundle\MagentoConnectorBundle\Reader\CategoryReader
    pim_magento_connector.reader.grouped_option.class:            Pim\Bundle\MagentoConnectorBundle\Reader\GroupedOptionReader
    pim_magento_connector.reader.attribute.class:                 Pim\Bundle\MagentoConnectorBundle\Reader\AttributeReader

services:
    pim_magento_connector.reader.doctrine.bulk_simple_product:
        parent: pim_base_connector.reader.doctrine.product
        class: %pim_base_connector.reader.doctrine.bulk_product.class%

    pim_magento_connector.reader.doctrine.bulk_configurable_product:
        parent: pim_base_connector.reader.doctrine.product
        class: %pim_base_connector.reader.doctrine.bulk_product.class%

    pim_magento_connector.reader.doctrine.bulk_product_association:
        parent: pim_base_connector.reader.doctrine.product
        class: %pim_base_connector.reader.doctrine.bulk_product.class%

    pim_magento_connector.reader.orm.category:
        class: %pim_magento_connector.reader.category.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.category.class%
            - '@pim_magento_connector.repository.category'
            - '@pim_catalog.manager.channel'

    pim_magento_connector.reader.orm.grouped_option:
        class: %pim_magento_connector.reader.grouped_option.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute_option.class%

    pim_magento_connector.reader.orm.attribute:
        class: %pim_magento_connector.reader.attribute.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute.class%
            - '@pim_magento_connector.merger.attribute_code_mapping'

    pim_magento_connector.reader.orm.family:
        class: %pim_base_connector.reader.orm.entity.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.family.class%
            - '@pim_magento_connector.merger.attribute_code_mapping'
