parameters:
    pim_magento_connector.cleaner.product.class:                  Pim\Bundle\MagentoConnectorBundle\Cleaner\MongoDBODM\ProductCleaner
    pim_magento_connector.reader.delta_product.class:             Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaProductReader
    pim_magento_connector.reader.delta_product_association.class: Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaProductReader
    pim_magento_connector.reader.delta_configurable.class:        Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaConfigurableReader

services:
    pim_magento_connector.reader.product_delta:
        class: %pim_magento_connector.reader.delta_product.class%
        parent: pim_base_connector.reader.doctrine.product
        arguments:
            - true
            - '@pim_magento_connector.repository.delta_product_export'

    pim_magento_connector.reader.delta_product_association:
        class: %pim_magento_connector.reader.delta_product_association.class%
        parent: pim_base_connector.reader.doctrine.product
        arguments:
            - false
            - '@pim_magento_connector.repository.delta_product_association_export'

    pim_magento_connector.reader.delta_configurable:
        class: %pim_magento_connector.reader.delta_configurable.class%
        parent: pim_base_connector.reader.doctrine.product
        arguments:
            - false
            - '@pim_magento_connector.repository.delta_configurable_export'
            - '@pim_magento_connector.repository.group'

    pim_magento_connector.cleaner.product:
        class: %pim_magento_connector.cleaner.product.class%
        parent: pim_magento_connector.item.magento_item_step
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.webservice.magento_soap_client_parameters_registry'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.product'
            - '@pim_catalog.repository.attribute'
